services:
  uptime_monitor:
    image: uptime-cloud:latest
    build:
      context: .
    secrets:
      - smtp_username
      - smtp_password
    environment:
      SMTP_USERNAME_FILE: /run/secrets/smtp_username
      SMTP_PASSWORD_FILE: /run/secrets/smtp_password
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    ports:
      - "8080:8080"  # Expose Prometheus metrics
    volumes:
      - ./config.json:/app/config.json:ro  # Bind
#     networks:
#       - loki-net
# networks:
#   loki-net:
#     external: true
secrets:
  smtp_username:
    external: true
  smtp_password:
    external: true